# Jekyll workshop-template https://github.com/evanwill/workshop-template
# based on minima theme https://github.com/jekyll/minima

title: S치ndor S칩v치g칩
description: > 
  Learn about GitHub pages and Jekyll. 
keywords: "github, github-pages, websites, static gen, hosting, html, workshop, gh-pages"

url: "https://sovagos.github.io" 

# author settings for cc-by
author: Sandor Sovago
github_username: sovagos
pub_year: 2017
repo: "https://github.com/sovagos/site"

# Build settings
markdown: kramdown

# figure include: {% include image.html file="cat.jpg" alt="kitten" cap="My cat" width="45%" %}
